import { Profile } from "@/lib/recodd/types";

// Categories: development, design, ui-ux, marketing, data-science, mobile-apps, webflow, consulting
// Each category has 5 freelancers

export const freelancers: Profile[] = [
  // ===== DEVELOPMENT (5 profiles) =====
  {
    id: 1,
    name: "Aarav Sharma",
    role: "Full Stack Developer",
    experience: "3 Years",
    budget: "₹200/hr",
    type: "freelancer",
    tags: ["React", "Node.js", "MongoDB", "Development"],
    location: "Remote · India",
    availability: "full-time",
  },
  {
    id: 2,
    name: "James Wilson",
    role: "Backend Developer",
    experience: "5 Years",
    budget: "₹280/hr",
    type: "freelancer",
    tags: ["Python", "Django", "PostgreSQL", "Development"],
    location: "Remote · US",
    availability: "contract",
  },
  {
    id: 3,
    name: "Elena Rodriguez",
    role: "Frontend Developer",
    experience: "4 Years",
    budget: "₹220/hr",
    type: "freelancer",
    tags: ["Vue.js", "TypeScript", "CSS", "Development"],
    location: "Remote · Spain",
    availability: "full-time",
  },
  {
    id: 4,
    name: "Rahul Verma",
    role: "DevOps Engineer",
    experience: "6 Years",
    budget: "₹350/hr",
    type: "freelancer",
    tags: ["AWS", "Docker", "Kubernetes", "Development"],
    location: "Hybrid · India",
    availability: "contract",
  },
  {
    id: 5,
    name: "Sophie Martin",
    role: "Software Developer",
    experience: "2 Years",
    budget: "₹180/hr",
    type: "freelancer",
    tags: ["Java", "Spring Boot", "MySQL", "Development"],
    location: "Remote · France",
    availability: "project",
  },

  // ===== DESIGN (5 profiles) =====
  {
    id: 6,
    name: "Anika Gupta",
    role: "Graphic Designer",
    experience: "4 Years",
    budget: "₹160/hr",
    type: "freelancer",
    tags: ["Illustrator", "Photoshop", "Branding", "Design"],
    location: "Remote · India",
    availability: "full-time",
  },
  {
    id: 7,
    name: "Marcus Brown",
    role: "Brand Designer",
    experience: "6 Years",
    budget: "₹240/hr",
    type: "freelancer",
    tags: ["Logo Design", "Brand Identity", "Design"],
    location: "Remote · UK",
    availability: "contract",
  },
  {
    id: 8,
    name: "Lisa Chang",
    role: "Visual Designer",
    experience: "3 Years",
    budget: "₹190/hr",
    type: "freelancer",
    tags: ["Figma", "Sketch", "Visual Design", "Design"],
    location: "Remote · Singapore",
    availability: "full-time",
  },
  {
    id: 9,
    name: "David Kim",
    role: "Illustration Designer",
    experience: "5 Years",
    budget: "₹210/hr",
    type: "freelancer",
    tags: ["Digital Art", "Character Design", "Design"],
    location: "Remote · Korea",
    availability: "project",
  },
  {
    id: 10,
    name: "Emma Thompson",
    role: "Creative Designer",
    experience: "4 Years",
    budget: "₹200/hr",
    type: "freelancer",
    tags: ["InDesign", "Print Design", "Layout", "Design"],
    location: "Remote · Australia",
    availability: "part-time",
  },

  // ===== UI/UX (5 profiles) =====
  {
    id: 11,
    name: "Sarah Jenkins",
    role: "UI/UX Designer",
    experience: "5 Years",
    budget: "₹140/hr",
    type: "freelancer",
    tags: ["Figma", "Product Design", "UI/UX"],
    location: "Remote · UK",
    availability: "contract",
  },
  {
    id: 12,
    name: "Arjun Mehta",
    role: "UX Researcher",
    experience: "4 Years",
    budget: "₹180/hr",
    type: "freelancer",
    tags: ["User Research", "Usability Testing", "UI/UX"],
    location: "Remote · India",
    availability: "full-time",
  },
  {
    id: 13,
    name: "Jennifer Lee",
    role: "Product Designer",
    experience: "6 Years",
    budget: "₹260/hr",
    type: "freelancer",
    tags: ["Prototyping", "Design Systems", "UI/UX"],
    location: "Remote · US",
    availability: "contract",
  },
  {
    id: 14,
    name: "Oliver Schmidt",
    role: "Interaction Designer",
    experience: "3 Years",
    budget: "₹200/hr",
    type: "freelancer",
    tags: ["Animation", "Micro-interactions", "UI/UX"],
    location: "Remote · Germany",
    availability: "full-time",
  },
  {
    id: 15,
    name: "Priya Singh",
    role: "UX Designer",
    experience: "5 Years",
    budget: "₹220/hr",
    type: "freelancer",
    tags: ["Wireframing", "User Flows", "UI/UX"],
    location: "Hybrid · India",
    availability: "project",
  },

  // ===== MARKETING (5 profiles) =====
  {
    id: 16,
    name: "Michael Adams",
    role: "Digital Marketer",
    experience: "5 Years",
    budget: "₹180/hr",
    type: "freelancer",
    tags: ["Google Ads", "Facebook Ads", "Marketing"],
    location: "Remote · US",
    availability: "full-time",
  },
  {
    id: 17,
    name: "Neha Kapoor",
    role: "SEO Specialist",
    experience: "4 Years",
    budget: "₹160/hr",
    type: "freelancer",
    tags: ["SEO", "Content Strategy", "Marketing"],
    location: "Remote · India",
    availability: "contract",
  },
  {
    id: 18,
    name: "Chris Taylor",
    role: "Social Media Manager",
    experience: "3 Years",
    budget: "₹140/hr",
    type: "freelancer",
    tags: ["Instagram", "TikTok", "Marketing"],
    location: "Remote · Canada",
    availability: "full-time",
  },
  {
    id: 19,
    name: "Ashley Wright",
    role: "Content Marketer",
    experience: "4 Years",
    budget: "₹170/hr",
    type: "freelancer",
    tags: ["Copywriting", "Email Marketing", "Marketing"],
    location: "Remote · UK",
    availability: "part-time",
  },
  {
    id: 20,
    name: "Vikram Rao",
    role: "Growth Hacker",
    experience: "6 Years",
    budget: "₹250/hr",
    type: "freelancer",
    tags: ["Analytics", "Conversion Optimization", "Marketing"],
    location: "Hybrid · India",
    availability: "project",
  },

  // ===== DATA SCIENCE (5 profiles) =====
  {
    id: 21,
    name: "Dr. Ananya Iyer",
    role: "Data Scientist",
    experience: "7 Years",
    budget: "₹320/hr",
    type: "freelancer",
    tags: ["Python", "Machine Learning", "Data Science"],
    location: "Remote · India",
    availability: "contract",
  },
  {
    id: 22,
    name: "Robert Chen",
    role: "ML Engineer",
    experience: "5 Years",
    budget: "₹350/hr",
    type: "freelancer",
    tags: ["TensorFlow", "Deep Learning", "Data Science"],
    location: "Remote · US",
    availability: "full-time",
  },
  {
    id: 23,
    name: "Maria Gonzalez",
    role: "Data Analyst",
    experience: "4 Years",
    budget: "₹200/hr",
    type: "freelancer",
    tags: ["SQL", "Tableau", "Data Science"],
    location: "Remote · Mexico",
    availability: "full-time",
  },
  {
    id: 24,
    name: "Thomas Anderson",
    role: "AI Researcher",
    experience: "6 Years",
    budget: "₹400/hr",
    type: "freelancer",
    tags: ["NLP", "Computer Vision", "Data Science"],
    location: "Remote · UK",
    availability: "project",
  },
  {
    id: 25,
    name: "Kavitha Nair",
    role: "BI Analyst",
    experience: "3 Years",
    budget: "₹180/hr",
    type: "freelancer",
    tags: ["Power BI", "Data Visualization", "Data Science"],
    location: "Hybrid · India",
    availability: "contract",
  },

  // ===== MOBILE APPS (5 profiles) =====
  {
    id: 26,
    name: "Kevin Park",
    role: "iOS Developer",
    experience: "5 Years",
    budget: "₹280/hr",
    type: "freelancer",
    tags: ["Swift", "SwiftUI", "Mobile Apps"],
    location: "Remote · Korea",
    availability: "full-time",
  },
  {
    id: 27,
    name: "Amit Patel",
    role: "Android Developer",
    experience: "4 Years",
    budget: "₹220/hr",
    type: "freelancer",
    tags: ["Kotlin", "Jetpack Compose", "Mobile Apps"],
    location: "Remote · India",
    availability: "contract",
  },
  {
    id: 28,
    name: "Rachel Green",
    role: "React Native Dev",
    experience: "3 Years",
    budget: "₹240/hr",
    type: "freelancer",
    tags: ["React Native", "Expo", "Mobile Apps"],
    location: "Remote · US",
    availability: "full-time",
  },
  {
    id: 29,
    name: "Sanjay Kumar",
    role: "Flutter Developer",
    experience: "4 Years",
    budget: "₹200/hr",
    type: "freelancer",
    tags: ["Flutter", "Dart", "Mobile Apps"],
    location: "Hybrid · India",
    availability: "project",
  },
  {
    id: 30,
    name: "Emily Watson",
    role: "Mobile UI Designer",
    experience: "5 Years",
    budget: "₹260/hr",
    type: "freelancer",
    tags: ["App Design", "Prototyping", "Mobile Apps"],
    location: "Remote · Australia",
    availability: "part-time",
  },

  // ===== WEBFLOW (5 profiles) =====
  {
    id: 31,
    name: "Daniel Foster",
    role: "Webflow Developer",
    experience: "4 Years",
    budget: "₹180/hr",
    type: "freelancer",
    tags: ["Webflow", "No-Code", "CMS"],
    location: "Remote · US",
    availability: "full-time",
  },
  {
    id: 32,
    name: "Sneha Reddy",
    role: "Webflow Designer",
    experience: "3 Years",
    budget: "₹160/hr",
    type: "freelancer",
    tags: ["Webflow", "Animations", "Responsive"],
    location: "Remote · India",
    availability: "contract",
  },
  {
    id: 33,
    name: "Laura Mitchell",
    role: "No-Code Expert",
    experience: "5 Years",
    budget: "₹220/hr",
    type: "freelancer",
    tags: ["Webflow", "Zapier", "Integrations"],
    location: "Remote · Canada",
    availability: "full-time",
  },
  {
    id: 34,
    name: "Raj Malhotra",
    role: "Webflow Specialist",
    experience: "2 Years",
    budget: "₹140/hr",
    type: "freelancer",
    tags: ["Webflow", "SEO", "Landing Pages"],
    location: "Hybrid · India",
    availability: "project",
  },
  {
    id: 35,
    name: "Sophie Davis",
    role: "Website Builder",
    experience: "4 Years",
    budget: "₹200/hr",
    type: "freelancer",
    tags: ["Webflow", "E-commerce", "Memberships"],
    location: "Remote · UK",
    availability: "part-time",
  },

  // ===== CONSULTING (5 profiles) =====
  {
    id: 36,
    name: "Richard Hayes",
    role: "Business Consultant",
    experience: "10 Years",
    budget: "₹400/hr",
    type: "freelancer",
    tags: ["Strategy", "Operations", "Consulting"],
    location: "Remote · US",
    availability: "contract",
  },
  {
    id: 37,
    name: "Meera Joshi",
    role: "Tech Consultant",
    experience: "8 Years",
    budget: "₹350/hr",
    type: "freelancer",
    tags: ["Digital Transformation", "IT Strategy", "Consulting"],
    location: "Hybrid · India",
    availability: "project",
  },
  {
    id: 38,
    name: "Andrew Clark",
    role: "Management Consultant",
    experience: "7 Years",
    budget: "₹380/hr",
    type: "freelancer",
    tags: ["Process Improvement", "Change Management", "Consulting"],
    location: "Remote · UK",
    availability: "full-time",
  },
  {
    id: 39,
    name: "Pooja Bansal",
    role: "Startup Advisor",
    experience: "6 Years",
    budget: "₹300/hr",
    type: "freelancer",
    tags: ["Fundraising", "GTM Strategy", "Consulting"],
    location: "Remote · India",
    availability: "part-time",
  },
  {
    id: 40,
    name: "William Brooks",
    role: "Financial Consultant",
    experience: "9 Years",
    budget: "₹420/hr",
    type: "freelancer",
    tags: ["Financial Planning", "Risk Analysis", "Consulting"],
    location: "Remote · Australia",
    availability: "contract",
  },
];

export const businesses: Profile[] = [
  {
    id: 101,
    name: "TechNova",
    role: "Looking for React Dev",
    experience: "Project Basis",
    budget: "₹2000 Fixed",
    type: "business",
    tags: ["React", "Next.js", "REST API"],
    location: "Remote",
    availability: "project",
  },
  {
    id: 102,
    name: "Creative Studio",
    role: "Need Logo Design",
    experience: "One-time",
    budget: "₹500 Fixed",
    type: "business",
    tags: ["Branding", "Logo"],
    location: "Remote",
    availability: "project",
  },
  {
    id: 103,
    name: "Growth Marketing",
    role: "SEO Specialist Needed",
    experience: "Contract",
    budget: "₹1500/mo",
    type: "business",
    tags: ["SEO", "Content Strategy"],
    location: "Hybrid · US",
    availability: "contract",
  },
  {
    id: 104,
    name: "StartUp Inc",
    role: "Mobile App MVP",
    experience: "3 Months",
    budget: "₹5000 Est",
    type: "business",
    tags: ["Flutter", "React Native"],
    location: "Remote",
    availability: "project",
  },
];
