import { Profile } from "@/lib/recodd/types";

export const freelancers: Profile[] = [
  {
    id: 1,
    name: "Aarav Sharma",
    role: "Full Stack Developer",
    experience: "3 Years",
    budget: "$20/hr",
    type: "freelancer",
    tags: ["React", "Node.js", "MongoDB"],
    location: "Remote · India",
    availability: "full-time",
  },
  {
    id: 2,
    name: "Sarah Jenkins",
    role: "UI/UX Designer",
    experience: "5 Years",
    budget: "$45/hr",
    type: "freelancer",
    tags: ["Figma", "Product Design"],
    location: "Remote · UK",
    availability: "contract",
  },
  {
    id: 3,
    name: "Mike Chen",
    role: "Video Editor",
    experience: "2 Years",
    budget: "$30/hr",
    type: "freelancer",
    tags: ["Premiere Pro", "After Effects"],
    location: "Remote · US",
    availability: "project",
  },
  {
    id: 4,
    name: "Priya Patel",
    role: "Content Writer",
    experience: "4 Years",
    budget: "$25/hr",
    type: "freelancer",
    tags: ["Tech Blogs", "SEO"],
    location: "Hybrid · India",
    availability: "part-time",
  },
];

export const businesses: Profile[] = [
  {
    id: 101,
    name: "TechNova",
    role: "Looking for React Dev",
    experience: "Project Basis",
    budget: "$2000 Fixed",
    type: "business",
    tags: ["React", "Next.js", "REST API"],
    location: "Remote",
    availability: "project",
  },
  {
    id: 102,
    name: "Creative Studio",
    role: "Need Logo Design",
    experience: "One-time",
    budget: "$500 Fixed",
    type: "business",
    tags: ["Branding", "Logo"],
    location: "Remote",
    availability: "project",
  },
  {
    id: 103,
    name: "Growth Marketing",
    role: "SEO Specialist Needed",
    experience: "Contract",
    budget: "$1500/mo",
    type: "business",
    tags: ["SEO", "Content Strategy"],
    location: "Hybrid · US",
    availability: "contract",
  },
  {
    id: 104,
    name: "StartUp Inc",
    role: "Mobile App MVP",
    experience: "3 Months",
    budget: "$5000 Est",
    type: "business",
    tags: ["Flutter", "React Native"],
    location: "Remote",
    availability: "project",
  },
];
